### ISSUE TITLE
Diagrams with Draw IO

### ISSUE THREAD

**Issue by rpinquie** [OPEN-NEXT/wp2.3_template#6]
Use Draw IO for Github drawings

https://github.com/jgraph/drawio-github

Need to evaluate the different integration alternatives.

IMO, the best solution would be to have 1 Draw IO repository associated to the project accessible through the hyperlink similar to the "Edit in diagrams.net" in the demo project

**Comment by amerezoji1362** [comment]
**Functional tree**
Use the link below to drwing your functional tree

https://app.diagrams.net/#G1EqpAVkNAmx8KzblQqgSOSND7bq5UQ069
[](url)

**Comment by amerezoji1362** [comment]
**Functional graph**
Use the link below to drow your functional graph

[https://app.diagrams.net/?libs=general;er#G1Vu8S5Zbqh19NMXCAXzxuCz5O-CRGU6Mm](url)

**Comment by amerezoji1362** [comment]
Use the link below to draw your architectural structure

[architectural structure](https://app.diagrams.net/#G1GCkQGQB4dYQCXf016Il42YpoE1dwrAtm)
